name: Java CI with Maven - Test and package"

on: 
  pull request:
    branches: [main]

jobs:
  build:
    run -on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: action/setup-java@v4
        with: 
          java-version: '21'
          distribution: 'corretto'
      - name: build with Maven
        run: mvn -B package --file pom.xml